name: Label pull requests

on:
  pull_request_target:

# limit permissions
permissions:
  contents: read
  pull-requests: write

jobs:
  labeler:
    runs-on: ubuntu-latest
    if: (github.actor != 'dependabot[bot]')
    steps:
    - uses: actions/labeler@v5
      with:
        sync-labels: false